# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scm_toolkit.middleware.current_user


class Migration(migrations.Migration):

    dependencies = [
        ('pareto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='user_id',
            field=models.ForeignKey(default=scm_toolkit.middleware.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
