# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareto', '0003_auto_20170131_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='user_id',
            field=models.CharField(default='1', editable=False, max_length=15),
        ),
    ]
