# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pareto', '0004_auto_20170131_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
