# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareto', '0006_auto_20170131_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='creator',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='last_editor',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
