# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareto', '0016_auto_20170201_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='item_desc',
            field=models.CharField(blank=True, default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='loc_desc',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='abc_multi_loc',
            name='loc_type',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
