# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pareto', '0018_abc_multiloc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc_multi_loc',
        ),
    ]
