# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0004_auto_20170114_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
