# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='site',
        ),
    ]
